sudo: required

language: java

addons:
  apt:
    packages:
      - xsltproc
      - libxml2-utils

services:
  - docker

before_install:
- git clone https://github.com/ramit-mitra/docker-drupal.git

install:
- cd docker-drupal
- docker-compose up -d
- docker ps

script:
  - java -version
  - whoami
  - ls -la
