version: '3'
services:
  web:
    build: web/
    restart: on-failure
    ports:
    - "80:8080"
    - "443:8081"
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ramit
      MYSQL_PASSWORD: 12345@1!